### ISSUE TITLE
Revision-Proyecto-NadiaFernandez

### ISSUE THREAD

**Issue by NadiaE-Fernandez** [KevinChosco/Proyecto_MercadoLiebre#1]
Puntos a Evaluar
1. Respecto a la estructura del sitio visualizar que contenga estos elementos cada
sección
Header:
● Logo: Si tiene
● Barra de búsqueda: Si tiene
● Comprá en cuotas y sin tarjeta de crédito: Si tiene
● Barra de navegación: Si tiene
● Ofertas: Si tiene
● Tiendas Oficiales: Si tiene
● Vender: Si tiene
● Ayuda: Si tiene
● Login: Si tiene
● Registro: Si tiene
● Mis compras: Si tiene
Main:
● Sección basada en las últimas visitas : Esta completo
● Sección de ofertas : Esta completo
Footer:
● Pagá con tarjeta o en efectivo: Completo
● Envío gratis desde $ 2.500: Completo
● Seguridad, de principio a fin : Completo
● Copyright © 1999-2022 MercadoLiebre S.R.L. :Completo
2. Haciendo foco en los estilos del pie de página (Footer):
● ¿El contenido de todos los artículos está centrado? Si
● ¿Los íconos tienen un tamaño de 2em y un margen inferior de separación de
10 píxeles? Le faltaria dar una clase al icono y aplicar el tamaño y el margen.
3. ¿El sitio se adapta a distintas resoluciones de pantalla? El sitio si se adapta a distintas resoluciones de pantalla.
4. ¿El sitio cuenta con un formulario de registro de usuarios? Si cuenta con un formulario de registro
5. ¿El sitio cuenta con un formulario de login? Si cuenta con un formulario de login , e incluso con un logo que le da personalidad.

3

6. ¿Se muestran mensajes de error cuando un usuario coloca información
equivocada en un campo de los formularios? no me aparece
7. ¿El search bar es un formulario? si
8. ¿Se utilizan animaciones y propiedades de transición de CSS? Si
9. Para terminar el feedback, menciona algunas cosas que crees que tu
compañero hizo bien. Felicitarlo porque llego a completar su mercadoliebre :)  le faltaria aplicar estilo al icono del footer y nada mas.
10.Por último, menciona algo que tu compañero podría mejorar. Algo para mejorar creo que nada solamente decir que felicidades y que siga asi durante todo el curso. Exitoss :)

**Comment by KevinChosco** [comment]
Muchas gracias!
