### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by Tetricslaughter** [KevinChosco/Proyecto_MercadoLiebre#2]
Header:
● Logo: ✅
● Barra de búsqueda:✅
● Comprá en cuotas y sin tarjeta de crédito: ✅
● Barra de navegación:✅
● Ofertas: ✅
● Tiendas Oficiales:✅
● Vender:✅
● Ayuda:✅
● Login:✅
● Registro:✅
● Mis compras:✅
Main:
● Sección basada en las últimas visitas : ✅
● Sección de ofertas :✅
Footer:
● Pagá con tarjeta o en efectivo:✅
● Envío gratis desde $ 2.500:✅
● Seguridad, de principio a fin :
● Copyright © 1999-2022 MercadoLiebre S.R.L. :✅
Haciendo foco en los estilos del pie de página (Footer):
● ¿El contenido de todos los artículos está centrado? ✅el contenido de los articulos esta centrado
● ¿Los íconos tienen un tamaño de 2em y un margen inferior de separación de
10 píxeles?✅si tienen el margen y el tamaño correcto
¿El sitio se adapta a distintas resoluciones de pantalla? ⏺️si, el sitio se adapta bien en distintas resoluciones
¿El sitio cuenta con un formulario de registro de usuarios?✅ si cuenta
¿El sitio cuenta con un formulario de login?✅no cuenta
¿Se muestran mensajes de error cuando un usuario coloca información
equivocada en un campo de los formularios? ❌no
¿El search bar es un formulario?✅si, lo es
¿Se utilizan animaciones y propiedades de transición de CSS?✅si se usaron
Para terminar el feedback, menciona algunas cosas que crees que tu
compañero hizo bien.
La estructura en general de la pagina esta correcta y bien elaborada,es responsivo inclusive en vistas de tablets y esta wonito y el codigo es bastante limpio y entendible
Por último, menciona algo que tu compañero podría mejorar.
si bien la pagina es altamente responsiva, el menu hamburguesa no se muestra bien,recomiendo cambiar el mediaquery a 390.

**Comment by KevinChosco** [comment]
Gracias por la recomendación!
